[versions]
ktor = "2.0.3"

[libraries]
graphql-java = { module = "com.graphql-java:graphql-java", version = "18.2" }

ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }